package com.khawi.base

const val DATABASE_NAME = "muslim_guide.db"
const val walkthrough_key = "walkthrough"
const val language_key = "language"
const val english_key = "en"
const val arabic_key = "ar"
const val finishedKey = "finished"
const val cancelledKey = "canceled"
const val acceptedKey = "accepted"
const val newKey = "new"
const val startKey = "started"
const val finishKey = "finished"
const val cancelByUserKey = "canceled_by_user"
const val cancelByDriverKey = "canceled_by_driver"
const val acceptOfferKey = "accept_offer"
const val rejectOfferKey = "reject_offer"
const val attendOfferKey = "attend"
const val notAttendOfferKey = "not_attend"
const val addOfferKey = "add_offer"
